# Generated by Django 5.0 on 2024-02-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comments',
            field=models.ManyToManyField(blank=True, to='client.comment'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='comments',
            field=models.ManyToManyField(blank=True, to='client.comment'),
        ),
    ]
