# Generated by Django 5.0 on 2024-02-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_options_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
