# Generated by Django 5.0 on 2024-02-29 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_todolist_changed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='client',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
