# Generated by Django 5.0 on 2024-03-01 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_todolist_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='todolists', to='client.client'),
        ),
    ]
