# Generated by Django 5.0 on 2024-02-29 22:47

import datetime
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelExplained',
            fields=[
                ('boolean', models.BooleanField(default=True, verbose_name='This a Boolean')),
                ('char', models.CharField(default='Dancan Ngaga', help_text='use your original names', max_length=255, unique=True, verbose_name='Full name: ')),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 2, 29, 22, 47, 30, 159372, tzinfo=datetime.timezone.utc))),
                ('decimal', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('email', models.EmailField(default='abc@gmail.com', max_length=300)),
                ('file', models.FileField(blank=True, default='C:/Users/Dancan Ngaga/Desktop/modelsmadesimple/static/img/blank_image.png', upload_to='uploads')),
                ('image', models.ImageField(blank=True, default='C:/Users/Dancan Ngaga/Desktop/modelsmadesimple/static/img/blank_image.png', upload_to='uploads')),
                ('integer', models.IntegerField(default=0)),
                ('positive_small_int', models.PositiveIntegerField(default=1)),
                ('slug', models.SlugField(blank=True)),
                ('text', models.TextField(default='I love Django')),
                ('url', models.URLField(default='.')),
                ('uuid1', models.UUIDField(default=uuid.uuid4)),
                ('uuid2', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+254797921698', max_length=128, region=None)),
            ],
        ),
    ]
