# Generated by Django 5.0 on 2024-03-01 17:59

import datetime
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_mymodel_delete_modelexplained'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='char',
            field=models.CharField(default='Dancan Ngaga', help_text='use your original names', max_length=255, unique=True, verbose_name='Full name: '),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 17, 59, 20, 445200, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='decimal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=300),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='file',
            field=models.FileField(blank=True, default='C:/Users/Dancan Ngaga/Desktop/modelsmadesimple/static/img/blank_image.png', upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='image',
            field=models.ImageField(blank=True, default='C:/Users/Dancan Ngaga/Desktop/modelsmadesimple/static/img/blank_image.png', upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='integer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+254797921698', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='positive_small_int',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='text',
            field=models.TextField(default='I love Django'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='url',
            field=models.URLField(default='.'),
        ),
    ]
