# Generated by Django 5.0 on 2024-03-01 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_mymodel_char_mymodel_date_mymodel_decimal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 18, 2, 25, 106731, tzinfo=datetime.timezone.utc)),
        ),
    ]
