# Generated by Django 5.0 on 2024-03-01 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_mymodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 18, 27, 21, 537092, tzinfo=datetime.timezone.utc)),
        ),
    ]
