# Generated by Django 5.0 on 2024-03-01 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_mymodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 19, 8, 0, 520151, tzinfo=datetime.timezone.utc)),
        ),
    ]
