# Generated by Django 5.0 on 2024-03-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_mymodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
